<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Login]]>
    </line>
    <line>
      <![CDATA[action2]]>
    </line>
    <line>
      <![CDATA[Loginout]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="94" started-at="2017-11-15T05:46:01Z" finished-at="2017-11-15T05:46:01Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="94" started-at="2017-11-15T05:46:01Z" finished-at="2017-11-15T05:46:01Z">
      <class name="jen.jenkins">
        <test-method status="PASS" signature="Login()[pri:0, instance:jen.jenkins@3fee9989]" name="Login" is-config="true" duration-ms="18" started-at="2017-11-15T11:16:01Z" finished-at="2017-11-15T11:16:01Z">
          <reporter-output>
            <line>
              <![CDATA[Login]]>
            </line>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="FAIL" signature="action2()[pri:0, instance:jen.jenkins@3fee9989]" name="action2" duration-ms="11" started-at="2017-11-15T11:16:01Z" finished-at="2017-11-15T11:16:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at jen.jenkins.action2(jenkins.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[action2]]>
            </line>
          </reporter-output>
        </test-method> <!-- action2 -->
        <test-method status="PASS" signature="LogOut()[pri:0, instance:jen.jenkins@3fee9989]" name="LogOut" is-config="true" duration-ms="1" started-at="2017-11-15T11:16:01Z" finished-at="2017-11-15T11:16:01Z">
          <reporter-output>
            <line>
              <![CDATA[Loginout]]>
            </line>
          </reporter-output>
        </test-method> <!-- LogOut -->
        <test-method status="SKIP" signature="action1()[pri:0, instance:jen.jenkins@3fee9989]" name="action1" duration-ms="1" started-at="2017-11-15T11:16:01Z" depends-on-methods="jen.jenkins.action2" finished-at="2017-11-15T11:16:01Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method jenkins.action1()[pri:0, instance:jen.jenkins@3fee9989] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method jenkins.action1()[pri:0, instance:jen.jenkins@3fee9989] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1092)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- action1 -->
      </class> <!-- jen.jenkins -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
